apiVersion: batch/v1
kind: CronJob
metadata:
  name: flask-cronjob
spec:
  schedule: "*/5 * * * *"  # every 5 minutes (example)
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: curl
              image: curlimages/curl:8.8.0
              args: ["-sS", "http://flask-service:80/"]

