apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: flask-hello-world
spec:
  selector:
    app: flask-hello-world
  type: ClusterIP   # Use LoadBalancer on cloud if you need external access
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

