{{- if and .Values.config.enabled .Values.config.data }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flask-hello-world.fullname" . }}
  labels:
    {{- include "flask-hello-world.labels" . | nindent 4 }}
data:
{{- toYaml .Values.config.data | nindent 2 }}
{{- end }}
